## Use xenial for Python3.7...
os: linux
dist: xenial
language: python
python:
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7

## Different distro to run pypy...
os: linux
language: python
python:
- pypy
# - pypy3 (errors out right now)

install:
- pip install --upgrade -q pip
- pip install --upgrade -q ciscoconfparse


script: make test

#matrix:
#  allow_failures:
    ## FIXME Python3.2 is broken (github issue #14)
#    - python: 3.2
