os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
 - pypy
# - pypy3 (errors out right now)

# http://docs.travis-ci.com/user/multi-os/
os:
 - linux

install:
 - pip install --upgrade -q pip
 - pip install --upgrade -q ciscoconfparse


script: make test

matrix:
  allow_failures:
    ## FIXME Python3.2 is broken (github issue #14)
    - python: 3.2
